### ISSUE TITLE
only for text data?

### ISSUE THREAD

**Issue by Warrior996** [liguge/Deep-Residual-Shrinkage-Networks-for-intelligent-fault-diagnosis-DRSN-#2]
Hello, thank you for your open source work.
I have a question, the code is only for text data, because I saw the use of conv1D, if I want to use image data, I have tried to modify conv1D and BatchNorm1d to conv2D and BatchNorm2d, but still error.
What else do I need to fix? Hope to get your answer.
Thanks!

**Comment by liguge** [comment]
It maybe help you:  https://cloud.tencent.com/developer/article/1813376

**Comment by Warrior996** [comment]
Thank you very much for your help！
